# This is a basic workflow to help you get started with Actions

name: DOCKER

on:
  push:
#    branches:
#      - master
#      - main
  pull_request:
#    branches:
#      - master
#      - main
  workflow_dispatch:

env:
  ECR: 636334651895.dkr.ecr.eu-central-1.amazonaws.com
  IMAGE: backend

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: AWS cli install action
        uses: chrislennon/action-aws-cli@1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set env
        run: |
          echo "TAG=${ECR}/${IMAGE}:$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Unit tests
        run: npm run test

      - name: E2e tests
        run: npm run test:e2e

      - name: Coverage test
        run: npm run test:cov

      - name: Docker build
        run: docker build -t $TAG -f .github/workflows/Dockerfile .

      - name: ECR login
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR

      - name: Push image
        run: docker push $TAG

